config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations"}

  devise_scope :sessions do
    get "users/sign_out", to: "home#index"
  end

  resources :users
  resources :recipes
  resources :tags
  resources :votes

  root 'home#index'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :votes

  def tag_list=(tags_string)
    tags_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def self.search_for(query)
      where('title LIKE :query OR directions LIKE :query OR ingredients LIKE :query', query: "%#{query}%")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :recipe
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
  has_many :votes

  private

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "30x30>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe

  validates :user_id, :uniqueness => { :scope => :recipe_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 before_action :configure_permitted_parameters, if: :devise_controller?

protected

  #  def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:user) << :image
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipe = Recipe.paginate(:page => params[:page] || 1, :per_page => params[:per_page] || 3)
    if params[:search]
      @recipes = Recipe.search_for(params[:search])
    else
      @recipes = Recipe.all
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
      @recipe.save
      flash[:notice] = "Recipe posted"
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = "Something went wrong"
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:notice] = "Recipe updated"
      redirect_to :back
    else
      flash[:alert] = "Something went wrong"
    end
  end

  def destroy
    if current_user.id = @recipe.user.id
      @recipe.destroy
      flash[:notice] = "Recipe deleted"
    else
      flash[:alert] = "Something went wrong"
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :ingredients, :directions, :time).merge(user_id: current_user.id)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    edit_user_path(resource)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @user = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def update
    @user = User.find(params[:id])
    if @user && @user.update(user_params)
      flash[:notice] = "Updated"
      redirect_to current_user
    else
      flash[:alert] = "There was a problem"
      render :edit
    end
  end

  def create
    @user = User.create(user_params)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:alert] = "User deleted"
      redirect_to root_path
    else
      flash[:alert] = "There was a problem"
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:fname, :lname, :email, :location, :favorite_cuisine, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = current_user.votes.where(:recipe_id => params[:vote][:recipe_id]).first
    @vote ||= current_user.votes.create(vote_params)
    @vote.update_attributes(:up => params[:vote][:up])
    redirect_to :back
  end

  private

  def vote_params
    params.require(:vote).permit(:up, :recipe_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def recipe_params
    params.require(:recipe).permit(:title, :directions, :ingredients, :time)
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/home/index.html.erb
<h1>Welcome to What's Cooking</h1>
<p>Start your cooking adventure below</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhatsCooking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <img id="logo-pic" src="http://cdn.flaticon.com/png/256/8101.png">
    <h2 id="logo">What's Cooking?</h2>
    <ul id="nav">
      <li>
        <h2><%= link_to 'Home', root_path %></h2>
      </li>
      <li>
        <h2><%= link_to 'Recipes', recipes_path %></h2>
      </li>
      <li>
        <h2><%= link_to 'About' %></h2>
      <li>
        <% if current_user %>
        <p>Hey <%= current_user.email %> |
          <%= image_tag current_user.image.url(:thumb) %>
        <%= link_to 'Profile', user_path(current_user) %> |
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        </p>
      </li>
    <% else %>
    <li>
      <p>
        <%= link_to 'sign in', new_user_session_path %> |
        <%= link_to 'sign up', new_user_registration_path %>
      </li>
    </p>
<% end %>
  </ul>
</header>

<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>
<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<div id="post-recipe">
<%= form_for @recipe do |r| %>
<p id="recipe-input"><%= r.label :title %></p>
<%= r.text_field :title %>
<p id="recipe-input"><%= r.label :ingredients %></p>
<%= r.text_area :ingredients %>
<p id="recipe-input"><%= r.label :directions %></p>
<%= r.text_area :directions %></br>
<p id="recipe-input"><%= r.label :time %></p>
<%= r.text_field :time %></br>
<p id="recipe-input"><%= r.label :tag_list %></p>
<%= r.text_field :tag_list %></br></br>
<%= r.submit %>
<% end %>
</div>

app/views/recipes/index.html.erb
<h2> Recipes </h2>
<%= button_to "Post a new recipe", new_recipe_path %>
<%= form_tag recipes_path, :method => 'get' do %>
  <p id="search-food">
    Search any ingredient, recipe or cuisine:

    <%= text_field_tag :search, params[:search] %></br>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<%= will_paginate @recipe %>
<ul>
  <% @recipes.each do |recipe| %>
  <li><%= link_to recipe.title, recipe_path(recipe) %></li>
  <% if current_user && current_user.votes.where(:recipe_id => recipe.id, :up => true). present? %>
    *
  <% else %>
    <%= link_to "+", votes_path(:vote => { :recipe_id => recipe.id, :up => true }), :method => :post %>
  <% end %>
  <% if current_user && current_user.votes.where(:recipe_id => recipe.id, :up => false).present? %>
    *
  <% else %>
    <%= link_to "-", votes_path(:vote => { :recipe_id => recipe.id, :up => false }), :method => :post %>

    Up: <%= recipe.votes.where(:up => true).count %>
    Down: <%= recipe.votes.where(:up => false).count %>
    Votes: <%= recipe.votes.where(:up => true).count - recipe.votes.where(:up => false).count %>
  </br>
</br>

  <% end %>
<% end %>
</ul>
<%= will_paginate @recipe %>

app/views/recipes/new.html.erb
<body id="post-recipe">
<h2 id="post-recipe-title">Post your Recipe</h2>
<%= render 'form' %>
</body>

app/views/recipes/show.html.erb
<body id="recipe-id">
<h3><%= @recipe.title %></h3>

<p>Ingredients: <%= @recipe.ingredients %></p>
<p>Directions: <%= @recipe.directions %></p>
<p>Time (minutes): <%= @recipe.time %></p>
<p>
  <p>Tags:</p>
  <% @recipe.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
</body>

app/views/tags/show.html.erb
<h2>Recipes tagged with <%= @tag.name %></h2>

<ul>
  <% @tag.recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe_path(recipe) %>
  <% end %>
</ul>

app/views/users/_form.html.erb
<%= form_for(@user, html: {multipart: true}) do |f| %>

<%= f.label :first_name %>
<%= f.text_field :fname %></br>
</br>
<%= f.label :last_name %>
<%= f.text_field :lname %></br>
</br>
<%= f.label :location %>
<%= f.text_field :location %></br>
</br>
<%= f.label :favorite_cuisine %>
<%= f.text_field :favorite_cuisine %></br>
</br>
<p>
  <%= f.label :image, "Attach an Image" %></br>
  <%= f.file_field :image %>
</p>
<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit your profile</h2>
<%= form_for @user do |f| %>

<%= f.label :first_name %>
<%= f.text_field :fname %></br>
</br>
<%= f.label :last_name %>
<%= f.text_field :lname %></br>
</br>
<%= f.label :location %>
<%= f.text_field :location %></br>
</br>
<%= f.label :favorite_cuisine %>
<%= f.text_field :favorite_cuisine %></br>
</br>
<%= f.label :image, "Attach an Image" %>
<%= f.file_field :image %></br>
</br>
<%= f.submit "Update" %>
<% end %>

app/views/users/new.html.erb
<h2>Make your Profile</h2>
<%= render 'form' %>

app/views/users/show.html.erb
<h2>Your Profile</h2>
<%= image_tag @user.image.url(:medium) %>
<h3><%= @user.fname %> <%= @user.lname %></h3>
<h3><%= current_user.email %></h3>
<h3>Location: <%= @user.location %></h3>
<h3>Favorite Food: <%= @user.favorite_cuisine %></h3>
<%= link_to "Edit Profile", edit_user_path %>